client_config_backend: settings
client_config:
  client_id: 474804517939-3trqao5mhpb75sb9j7fsudaro85qtm5d.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
